[project]
name = "exp-psych-programs-25s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.1.4",
    "otree>=5.11.1",
    "polars>=1.25.2",
    "python-pptx>=1.0.2",
    "requests>=2.32.3",
]
